### ISSUE TITLE
/usr/bin/env: k8: No such file or directory?

### ISSUE THREAD

**Issue by tarak77** [lh3/hickit#11]
Hi,
I am new to javascript shells. I downloaded the precompiled binaries for k8 on Linux and then based on https://github.com/lh3/hickit/issues/5#issuecomment-419579074 ,trying to run with the following command:
```
[tshisode@darwin hickit-master]$ /home/tshisode/k8-0.2.5/k8-Linux ./hickit.js sam2seg -v cast_C57BL6J.phased_SNP.tsv ./4CSE-101_hickit/aln.sam.gz | ./hickit.js chronly - | gzip > ./4CSE-101_hickit/contacts.seg.gz
/usr/bin/env: k8: No such file or directory
```
Am i missing something?

**Comment by tanlongzhi** [comment]
You missed adding `k8` during your second call of `hickit.js` (namely `./hickit.js chronly -`).

Alternatively, you can rename your `k8-Linux` to `k8` and put it under your path (for example, to `~/bin/`). Doing so will allow you to use `./hickit.js` directly.

**Comment by tarak77** [comment]
Oh, got it. Thanks!
