### ISSUE TITLE
how to calculate RMSD using hickit

### ISSUE THREAD

**Issue by ZhangJiankun21** [lh3/hickit#18]
Hello @lh3 @tanlongzhi 
In the Dipc code written by Tan, Align.py can calculate the root mean square deviation of the three-dimensional structure of each round of modeling at a given final resolution. Does hickit have a similar function? Or how do we determine the final resolution we can get is reliable when using hickit? 
Thanks for the help!

**Comment by tanlongzhi** [comment]
On the dip-c side, I recent wrote some format-conversion scripts, so you can always convert hickit contacts and 3D structures for analysis in dip-c:

```sh
scripts/hickit_impute_pairs_to_con.sh impute.pairs.gz
for rep in `seq 1 3`
do
  scripts/hickit_3dg_to_3dg_rescale_unit.sh 20k.${rep}.3dg
  dip-c clean3 -c impute.con.gz 20k.${rep}.dip-c.3dg > 20k.${rep}.clean.3dg
done
dip-c align -o aligned.20k. 20k.*.clean.3dg 2> 20k.align.log > 20k.align.color
```

I'll update dip-c's manual page when our next paper comes out in the upcoming months.

**Comment by ZhangJiankun21** [comment]
Thanks!
