### ISSUE TITLE
Where can I find the algorithmic details?

### ISSUE THREAD

**Issue by renxwise** [lh3/hickit#22]
3D reconstruction from contacts is nontrivial, so where can I find the algorithmic details behind hickit?

**Comment by lh3** [comment]
Similar to [nuc_dynamics](https://github.com/tjs23/nuc_dynamics), which is published.

**Comment by tanlongzhi** [comment]
The detailed design of [nuc_dynamics](https://github.com/tjs23/nuc_dynamics) can be found in the Supplementary Information ([PDF](https://static-content.springer.com/esm/art%3A10.1038%2Fnature21429/MediaObjects/41586_2017_BFnature21429_MOESM26_ESM.pdf)) of Stevens *et al.* **Nature** 2017 ([paper](https://www.nature.com/articles/nature21429)).

A major speed improvement of this repo is to use AVL tree to calculate repulsive forces (i.e. volume exclusion). This implementation can be found starting from [this line in `fdg.c`](https://github.com/lh3/hickit/blob/master/fdg.c#L265). The [nuc_dynamics](https://github.com/tjs23/nuc_dynamics) counterpart can be found starting from [this line of their code](https://github.com/tjs23/nuc_dynamics/blob/master/dyn_util.pyx#L17). As a result, 3D modeling is very fast in this repo.

**Comment by renxwise** [comment]
Thanks for your replies. The speed acceleration is impressing.

**Comment by renxwise** [comment]
Following your guide, I have gotten the main idea of the algorithm. But I still have a question. Is the repulsive force calculated for each pair of particles so that the replacement of AVL tree greatly accelerates the speed? Am I correct?

**Comment by lh3** [comment]
Repulsive force is only calculated for particles close enough.

**Comment by renxwise** [comment]
Thanks. I did not state clearly my point in the last comment. What I mean is that in nuc_dynamics each pair of particles are examined. But in hickit AVL tree is used to calculate only particles close enough. Is my guess correct?

**Comment by lh3** [comment]
nuc_dynamics uses a kd-tree. I don't now why nuc_dynamics is slower.
