### ISSUE TITLE
Do you recommend bwa mem with or without the -5 option for aligning normal hi-c data

### ISSUE THREAD

**Issue by jelber2** [lh3/hickit#23]
I noticed that in https://github.com/lh3/hickit/blob/e8d87c4e2bb8cef1789098eff64501339db97e0a/README.md,

#### <a name="aln-hic"></a>Aligning Hi-C reads

If have normal Hi-C reads, you can align directly with bwa-mem:
```sh
bwa mem hs37d5.fa read1.fq.gz read2.fq.gz | gzip > aln.sam.gz
```
Is there some reason not to use the `-5` option for aligning normal hi-c read pairs?

**Comment by lh3** [comment]
To hickit, this option doesn't matter.

**Comment by jelber2** [comment]
Okay, thank you very much for the prompt response!
