### ISSUE TITLE
Working on my haploid dataset

### ISSUE THREAD

**Issue by tarak77** [lh3/hickit#3]
Hello, 

I am continuing the issue 1 from dip-c repo over here. I am trying to generate 3d structures for haploid cell data using hickit using bam2pairs script for converting my haploid cell .bam file(unsorted) to .pairs file and then the following command for generating coarser output at say 250kb:

**[tshisode@darwin hickit-0.1_x64-linux]$ ./hickit -i NXT-43.new.pairs -r1m -c1 -b4m -b1m -b250k -O out.3dg**

I just implement one round of filtering isolated contacts by removing options "-r10m -c5" to get enough number of contacts. But even after doing so, i get the following error:

**[M::hk_map_read] read 2685869 pairs
[M::hk_pair_filter_close_legs] filtered out 26532/2685869 pairs with close legs
[M::hk_pair_dedup] duplicate rate: 95.61% = 2542685 / 2659337
[M::hk_pair_filter_isolated] threshold: 1; filtered out 10754/116652 isolated pairs
hickit: bin.c:34: hk_bmap_set_offcnt: Assertion `m && m->d && m->beads' failed.
Aborted (core dumped)**

I even tried giving "-r500k -c1" option, but even after doing so, i get similar error.

Any help will be great! THanks.

P.S. i have also attached my sample_pairs file with first 100 lines from the .pairs file
[sample_pairs.txt](https://github.com/lh3/hickit/files/2350590/sample_pairs.txt)

**Comment by lh3** [comment]
It would be good to send me `out.pairs` generated with the following command line
```sh
./hickit -i NXT-43.new.pairs -r1m -c1 -o out.pairs
```
Thanks.

**Comment by tarak77** [comment]
Sure, 
[out.pairs.tar.gz](https://github.com/lh3/hickit/files/2350645/out.pairs.tar.gz)

**Comment by lh3** [comment]
Thanks. Is it mouse? You need to add chromosome names and lengths to the pairs header like (this is for human):
```sh
#chromosome: 1 249250621
#chromosome: 2 243199373
#chromosome: 3 198022430
#chromosome: 4 191154276
#chromosome: 5 180915260
```
Otherwise, hickit doesn't know chromosome lengths.

**Comment by lh3** [comment]
In your new sample_pairs2.txt, "chromosome" is mis-spelled as "chromsome" ("o" is missing). Anyway, this is a bug on my side to begin with. It should be "#chromsize" according to the pairs spec. I have just pushed a new change. It should work with input using "#chromsize:". It is working on my machine.

**Comment by lh3** [comment]
To be clear, the header should be:
```txt
## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: 1 197195432
#chromsize: 2 181748087
#chromsize: 3 159599783
#chromsize: 4 155630120
#chromsize: 5 152537259
#chromsize: 6 149517037
#chromsize: 7 152524553
#chromsize: 8 131738871
#chromsize: 9 124076172
#chromsize: 10 129993255
#chromsize: 11 121843856
#chromsize: 12 121257530
#chromsize: 13 120284312
#chromsize: 14 125194864
#chromsize: 15 103494974
#chromsize: 16 98319150
#chromsize: 17 95272651
#chromsize: 18 90772031
#chromsize: 19 61342430
#chromsize: X 166650296
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 n_neighbors n_nei_corner
```

**Comment by tarak77** [comment]
Is this the header for the initial .pairs file or the out.pairs file?

**Comment by lh3** [comment]
For both. As the initial .pairs file already has this header, you don't need to make any changes. Please check out the master. It has the bugfix.

**Comment by tarak77** [comment]
Sorry but it is still not clear to me. I am running hickit on version r273, 

1. **My NXT-43.new.pairs input file has header:**
## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: 1 197195432
#chromsize: 2 181748087
#chromsize: 3 159599783
#chromsize: 4 155630120
#chromsize: 5 152537259
#chromsize: 6 149517037
#chromsize: 7 152524553
#chromsize: 8 131738871
#chromsize: 9 124076172
#chromsize: 10 129993255
#chromsize: 11 121843856
#chromsize: 12 121257530
#chromsize: 13 120284312
#chromsize: 14 125194864
#chromsize: 15 103494974
#chromsize: 16 98319150
#chromsize: 17 95272651
#chromsize: 18 90772031
#chromsize: 19 61342430
#chromsize: X 166650296
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2

**Note that in above, the last row #columns- has only 7 entries**

2. **I changed by out.pairs file header manually to** 
## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: 1 197195432
#chromsize: 2 181748087
#chromsize: 3 159599783
#chromsize: 4 155630120
#chromsize: 5 152537259
#chromsize: 6 149517037
#chromsize: 7 152524553
#chromsize: 8 131738871
#chromsize: 9 124076172
#chromsize: 10 129993255
#chromsize: 11 121843856
#chromsize: 12 121257530
#chromsize: 13 120284312
#chromsize: 14 125194864
#chromsize: 15 103494974
#chromsize: 16 98319150
#chromsize: 17 95272651
#chromsize: 18 90772031
#chromsize: 19 61342430
#chromsize: X 166650296
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 n_neighbors n_nei_corner

3. IMplementing
 ./hickit -i NXT-43.new.pairs -r1m -c1 -b4m -b1m -b250k -O out.3dg
or
./hickit -i out.pairs -r1m -c1 -b4m -b1m -b250k -O out.3dg
still gives error!

I think i am missing something ?

**Comment by lh3** [comment]
Github head is r276, not r273.

**Comment by lh3** [comment]
Forgot to say, you need to run "git pull" to get the latest code.

**Comment by tarak77** [comment]
Ah, my bad. 
So I am trying to run hickit on my Mac. After cloning the new repository(version r276), and the mentioned header(above) for NXT-43.new.pairs file, I get an error:
```
Taraks-MacBook-Pro:hickit tarakshisode$ ./hickit -i NXT-43.new.pairs -r1m -c1 -b4m -b1m -b250k -O out.3dg
Assertion failed: (m), function main, file main.c, line 98.
Abort trap: 6
```
Also when trying to get the out.pairs file:
```
Taraks-MacBook-Pro:hickit tarakshisode$ ./hickit -i NXT-43.new.pairs -r1m -c1 -o out.pairs
Assertion failed: (m), function main, file main.c, line 98.
Abort trap: 6

```
Thanks for your help!

**Comment by lh3** [comment]
This means hickit fails to open the input file. Could you check if the file exists and contains actual data?

**Comment by tarak77** [comment]
Yes it does exists with a size of 191.5MB

**Comment by lh3** [comment]
Then I don't know. The change has nothing to do with the following command line:
```sh
./hickit -i NXT-43.new.pairs -r1m -c1
```
and that assertion error could only be triggered by a missing file (or a file that you can't read). On my end, it works normally.

**Comment by tarak77** [comment]
I regenerated the input pairs file and then it works now! Thank you very much

**Comment by tarak77** [comment]
Is there a way to visualize the .3dg file? using pymol or chimera?

**Comment by lh3** [comment]
You can convert .3dg to .cif with dip-c (see dip-c documentations for details):
```sh
# color by chromosome number and visualize as mmCIF
dip-c color -n color/hg19.chr.txt impute3.round4.clean.3dg | dip-c vis -c /dev/stdin impute3.round4.clean.3dg > impute3.round4.clean.n.cif
```
You may also use hickit's lightweight viewer. On mac:
```sh
make clean && make gl=1
./hickit -I in.3dg --view
```
Your "out.pairs" looks like this (not sure if this is expected; I know little about mESC cells):

![screen shot 2018-09-05 at 00 39 17](https://user-images.githubusercontent.com/480346/45071421-29f75400-b0a4-11e8-826e-29d89301a186.png)

**Comment by tarak77** [comment]
Looks good! Yes these are from mitotic cells, so we should expect a dense/cylindrical packing of the chromosomes.

**Comment by tarak77** [comment]
Hey!
I am trying to use dip-c for converting my .3dg file to .cif for visualizing in pymol using the following command, with the error I get

```
Taraks-MacBook-Pro:dip-c tarakshisode$ ./dip-c color -n ./NXT-43.250kb/mm9.chr.txt ../hickit/NXT-43.250kb.hickit.3dg | dip-c vis -c /dev/stdin ../hickit/NXT-43.250kb.hickit.3dg > ./NXT-43.250kb/NXT-43.250kb.dip-c.cif
-bash: dip-c: command not found
Traceback (most recent call last):
  File "./dip-c", line 122, in <module>
    main()
  File "./dip-c", line 73, in main
    return_value = color.color(sys.argv[1:])
  File "/Users/tarakshisode/dip-c/color.py", line 127, in color
    g3d_data = file_to_g3d_data(open(args[0], "rb"))
  File "/Users/tarakshisode/dip-c/classes.py", line 1419, in file_to_g3d_data
    g3d_data.add_g3d_particle(string_to_g3d_particle(g3d_file_line.strip()))
  File "/Users/tarakshisode/dip-c/classes.py", line 1214, in string_to_g3d_particle
    hom_name, ref_locus, x, y, z = g3d_particle_string.split("\t")
TypeError: a bytes-like object is required, not 'str'
```

Why is that so?

**Comment by tanlongzhi** [comment]
Can you attach your `NXT-43.250kb.hickit.3dg` file (if larger than 10MB, please gzip; if still too large, at least part of it)? I suspect it’s because of the difference in naming the two homologs between the two repos, which can be easily fixed.

**Comment by tarak77** [comment]
Sure, 
[NXT-43.250kb.hickit.3dg.zip](https://github.com/lh3/hickit/files/2357263/NXT-43.250kb.hickit.3dg.zip)

**Comment by tanlongzhi** [comment]
You will need to run the following line to reformat the `3dg` file first, because dip-c can't read the headers and can only work with diploid data. In the following line, I arbitrarily specified all your haploid chromosomes as paternal (for example, `1(pat)`).
```sh
grep -v "^#" hickit.3dg | awk -F'[\t,]' -v OFS='\t' '{print $1 "(pat)",$2,$3,$4,$5}' > dip-c.3dg
```

Afterwards, you can run `dip-c color` and `dip-c vis` normally. Your file looks like the following in PyMol:
<img width="972" alt="nxt-43 250kb hickit n cif pymol" src="https://user-images.githubusercontent.com/2436999/45186262-dd725c80-b1fa-11e8-908e-0fbc3ad3c080.png">

Remember to add the `set connect_mode, 4` line to your PyMol start-up script (`.pymolrc`). Please see the paper's supplement or the newest dip-c README.

The PyMol script to style the above screenshot was:
```python
as sticks, all
set_bond stick_radius, 0.03, all
spectrum b, rainbow, all, 1, 20
```

**Comment by tarak77** [comment]
I see, after converting to proper header
```
1(pat)	0	1.079842	0.121320	-0.825316
1(pat)	3000000	0.990983	0.004892	-0.679638
1(pat)	3250000	1.057732	-0.039005	-0.586504
1(pat)	3500000	1.070921	-0.030389	-0.656131
1(pat)	3750000	1.041031	-0.097680	-0.630564
1(pat)	4000000	1.002650	-0.089433	-0.611659
1(pat)	4250000	1.093020	-0.030386	-0.569529
1(pat)	4500000	1.065441	-0.028860	-0.619866
1(pat)	4750000	1.080859	-0.061910	-0.641022

```
and then running the code

```
(py2) Taraks-MacBook-Pro:dip-c tarakshisode$ ./dip-c color -n ./NXT-43.250kb/mm9.chr.txt ./NXT-43.250kb/NXT-43.250kb.dip-c.3dg | dip-c vis -c /dev/stdin ./NXT-43.250kb/NXT-43.250kb.dip-c.3dg > ./NXT-43.250kb/NXT-43.250kb.dip-c.cif
-bash: dip-c: command not found
[M::color] read a 3D structure with 10131 particles at 250000 bp resolution
[M::color] analyzed 1000 particles (9.87%)
[M::color] analyzed 2000 particles (19.74%)
[M::color] analyzed 3000 particles (29.61%)
[M::color] analyzed 4000 particles (39.48%)
[M::color] analyzed 5000 particles (49.35%)
[M::color] analyzed 6000 particles (59.22%)
[M::color] analyzed 7000 particles (69.09%)
[M::color] analyzed 8000 particles (78.97%)
[M::color] analyzed 9000 particles (88.84%)
[M::color] analyzed 10000 particles (98.71%)
[M::color] writing 0 colors (0.0%)
[M::__main__] command: ./dip-c color -n ./NXT-43.250kb/mm9.chr.txt ./NXT-43.250kb/NXT-43.250kb.dip-c.3dg
[M::__main__] finished in 0.2 sec
```

My .cif file looks empty? Any help

**Comment by tanlongzhi** [comment]
You may have the same typo as the one in your [corresponding thread](https://github.com/tanlongzhi/dip-c/issues/3#issuecomment-419256852) in the dip-c repo.

**Comment by tarak77** [comment]
Got it! Thank you very much

**Comment by jijibio** [comment]
Hi,

I am getting error at the end while running the following command, I have used SRR7226683_1 and SRR7226683_2  fastq files as input

./hickit_new -i aln.sam.gz_hickit.gz -Sr1m -c1 -r10m -c5 -b4m -b1m -b200k -D5 -b50k -D5 -b20k -O out.3dg

[M::hk_map_read] read 1180101 pairs
[M::hk_pair_filter_close_legs] filtered out 0/1180101 pairs with close legs
[M::hk_pair_dedup] duplicate rate: 0.00% = 0 / 1180101
hickit_new: main.c:188: main: Assertion `(m->cols & 0x3c) == 0x3c' failed.
Aborted

It would be great if anyone can provide some suggestion 

Regards,
JK

**Comment by tanlongzhi** [comment]
Hi JK,
Can you attach some example lines from your `aln.sam.gz_hickit.gz`? It's unclear from your command or file name what types of data it is.

**Comment by jijibio** [comment]
Hi,
Here are some lines from aln.sam_hickit.gz

## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: chr10 129993255
#chromsize: chr11 121843856
#chromsize: chr12 121257530
#chromsize: chr13 120284312
#chromsize: chr14 125194864
#chromsize: chr15 103494974
#chromsize: chr16 98319150
#chromsize: chr17 95272651
#chromsize: chr18 90772031
#chromsize: chr19 61342430
#chromsize: chr1 197195432
#chromsize: chr2 181748087
#chromsize: chr3 159599783
#chromsize: chr4 155630120
#chromsize: chr5 152537259
#chromsize: chr6 149517037
#chromsize: chr7 152524553
#chromsize: chr8 131738871
#chromsize: chr9 124076172
#chromsize: chrX 166650296
#chromsize: chrY 15902555
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2
.       chr10   3000348 chr10   7325007 +       -
.       chr10   3000372 chr10   3013555 -       -
.       chr10   3000419 chr10   3047706 -       -
.       chr10   3000638 chr10   3004593 -       -
.       chr10   3000891 chr10   3013958 +       -

**Comment by lh3** [comment]
If this is haploid data, don't use `-S`.

**Comment by tanlongzhi** [comment]
It seems your file doesn't have any haplotype information. What's your code to generate this file? A problem must have occurred there.

**Comment by tanlongzhi** [comment]
> If this is haploid data, don't use `-S`.

@lh3 I just checked, [SRR7226683](https://www.ncbi.nlm.nih.gov/sra/?term=SRR7226683) should be diploid (GM12878).

**Comment by lh3** [comment]
Thanks, @tanlongzhi. As this is diploid data, you need to generate the .pairs file with phasing information (with `hickit.js sam2seg -v`) and use `-u` to impute missing phases before applying `-S`.

**Comment by jijibio** [comment]
Hi ,
Sorry for the confusion , the input files are different its not this  SRR7226683 
 my whole commands are:

./k8 hickit.js sam2seg aln.sam.gz > aln.sam_sam2seg
./k8 hickit.js chronly aln.sam_sam2seg > aln.sam_chronly
gzip aln.sam_chronly
./hickit_new -i aln.sam_chronly.gz -o aln.sam_hickit
bgzip aln.sam_hickit
hickit -i aln.sam_hickit.gz -Sr1m -c1 -r10m -c5 -b4m -b1m -b200k -D5 -b50k -D5 -b20k -O out.3dg

Regards,
JK

**Comment by lh3** [comment]
Either way – if it is haploid data, don't use `-S`; if it is diploid data, run `hickit.js sam2seg -v` and impute with `hickit -u`.

**Comment by jijibio** [comment]
Hi,

./hickit_new -i aln.sam_hickit.gz -r1m -c1 -r10m -c5 -b4m -b1m -b200k -D5 -b50k -D5 -b20k -O out.3dg

Output:
[M::hk_map_read] read 25876164 pairs
[M::hk_pair_filter_close_legs] filtered out 0/25876164 pairs with close legs
[M::hk_pair_dedup] duplicate rate: 0.00% = 0 / 25876164
[M::hk_pair_filter_isolated] threshold: 1; filtered out 142232/25876164 isolated pairs
[M::hk_pair_filter_isolated] threshold: 5; filtered out 6/25733932 isolated pairs
[M::hk_bmap_gen] generated 662 beads
hickit_new: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed.
Aborted

**Comment by lh3** [comment]
Is this a male mouse or female? If it is male, I am afraid that I need you .pairs file. First time see an assertion failure at this point.

Also, if this is public data, give us the accession number and the ploidy of the sample.

**Comment by lh3** [comment]
If this is haploid mouse, I guess it can only have chrX. Then it is a female. In this case, you should run `hickit.js chronly -y` to filter out chrY. If you see the same assertion failure, I may need your .pairs file.

**Comment by lh3** [comment]
Is this haploid or diploid?

**Comment by lh3** [comment]
Saw the "bulk" part. No, hickit won't work on bulk Hi-C.

**Comment by jijibio** [comment]
Hi,
Can you let me know, why it wont work on Bulk if the information is the same?

**Comment by tanlongzhi** [comment]
Here the 3D modeling function of hickit, which is similar to that in [nuc_dynamics](https://github.com/TheLaueLab/nuc_dynamics) and in [Nagano et al. 2017](https://www.nature.com/articles/nature23001), seeks a 3D genome structure that satisfies nearly all contacts of a contact map.

In bulk Hi-C, however, the contact map is an average of many cells with different 3D structures. It is impossible to find a single structure that satisfies nearly all these contacts.

You can of course still use other functions of hickit, for example extraction of contacts and their haplotype information from sequencing reads, on bulk Hi-C. It's only haplotype imputation and 3D modeling that doesn't apply to bulk.

**Comment by XiongGZ** [comment]
> Hi,
> 
> ./hickit_new -i aln.sam_hickit.gz -r1m -c1 -r10m -c5 -b4m -b1m -b200k -D5 -b50k -D5 -b20k -O out.3dg
> 
> Output: [M::hk_map_read] read 25876164 pairs [M::hk_pair_filter_close_legs] filtered out 0/25876164 pairs with close legs [M::hk_pair_dedup] duplicate rate: 0.00% = 0 / 25876164 [M::hk_pair_filter_isolated] threshold: 1; filtered out 142232/25876164 isolated pairs [M::hk_pair_filter_isolated] threshold: 5; filtered out 6/25733932 isolated pairs [M::hk_bmap_gen] generated 662 beads hickit_new: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed. Aborted

@lh3 I met the same bug, and I looked at the bin.c
![11c9067d23cb7c878179d0ca4115d52](https://github.com/lh3/hickit/assets/63765061/b7533936-2df3-47a6-8cd3-9d4b85e92717)

What can I do to solve this problem?
I can provide the pair and impute file

**Comment by zcq23** [comment]
I met the same bug too😭😭😭in my code: hickit -s${rep} -i ${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz -Sr1m -c1 -r10m -c2 -b4m \

To test which step was wrong, I run them step by step: 
hickit -i ${OUTPUT}/structure/SRR25505065.impute.pairs_with_chromsize.gz -Sr1m -c1 -o out.pairs √
hickit -i out.pairs -r10m -c2 -o out2.pairs √
hickit -i out2.pairs -b4m -o out3.pairs ×
and I met the bug "hickit: bin.c:70: hk_bmap_pos2bid: Assertion `pos < m->beads[hi].en' failed." in the last one, it is so strange!
my SRR25505065.impute.pairs_with_chromsize.gz is:
## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromsize: chr1 197195432
#chromsize: chr2 181748087
#chromsize: chr3 159599783
#chromsize: chr4 155630120
#chromsize: chr5 152537259
#chromsize: chr6 149517037
#chromsize: chr7 152524553
#chromsize: chr8 131738871
#chromsize: chr9 124076172
#chromsize: chr10 129993255
#chromsize: chr11 121843856
#chromsize: chr12 121257530
#chromsize: chr13 120284312
#chromsize: chr14 125194864
#chromsize: chr15 103494974
#chromsize: chr16 98319150
#chromsize: chr17 95272651
#chromsize: chr18 90772031
#chromsize: chr19 61342430
#chromsize: chrX 166650296
#chromsize: chrY 91744698
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 phase0 phase1 phase_prob00 phase_prob01 phase_prob10 phase_prob11
.       chr1    3016884 chr1    52750084        +       +       0       1       0.000   1.000   0.000   0.000
.       chr1    3023157 chr1    3557230 +       +       0       0       1.000   0.000   0.000   0.000
.       chr1    3028456 chr1    3177837 +       +       1       1       0.000   0.000   0.000   1.000
.       chr1    3033910 chr1    92724777        +       +       1       .       0.000   0.000   0.122   0.878
.       chrX    169915040       chrY    90809054        +       +       1       0       0.000   0.000   1.000   0.000
.       chrX    170005138       chrY    90805145        +       +       1       0       0.000   0.000   1.000   0.000


my sample is male, single-cell and diploid, and I run hickit.js chronly - | hickit.js bedflt ${PAR} - |,  hickit.js sam2seg -v and hickit -u all before. The last sucessful output file "out2.pairs" is: 
## pairs format v1.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#chromosome: chr1a 197195432
#chromosome: chr1b 197195432
#chromosome: chr2a 181748087
#chromosome: chr2b 181748087
#chromosome: chr3a 159599783
#chromosome: chr3b 159599783
#chromosome: chr4a 155630120
#chromosome: chr4b 155630120
#chromosome: chr5a 152537259
#chromosome: chr5b 152537259
#chromosome: chr6a 149517037
#chromosome: chr6b 149517037
#chromosome: chr7a 152524553
#chromosome: chr7b 152524553
#chromosome: chr8a 131738871
#chromosome: chr8b 131738871
#chromosome: chr9a 124076172
#chromosome: chr9b 124076172
#chromosome: chr10a 129993255
#chromosome: chr10b 129993255
#chromosome: chr11a 121843856
#chromosome: chr11b 121843856
#chromosome: chr12a 121257530
#chromosome: chr12b 121257530
#chromosome: chr13a 120284312
#chromosome: chr13b 120284312
#chromosome: chr14a 125194864
#chromosome: chr14b 125194864
#chromosome: chr15a 103494974
#chromosome: chr15b 103494974
#chromosome: chr16a 98319150
#chromosome: chr16b 98319150
#chromosome: chr17a 95272651
#chromosome: chr17b 95272651
#chromosome: chr18a 90772031
#chromosome: chr18b 90772031
#chromosome: chr19a 61342430
#chromosome: chr19b 61342430
#chromosome: chrX 166650296
#chromosome: chrY 91744698
#columns: readID chr1 pos1 chr2 pos2 strand1 strand2 n_neighbors n_nei_corner
.       chr1a   3023157 chr1a   3557230 +       +       279     5
.       chr1a   3160608 chr1a   3164536 +       +       275     0
.       chr1a   3164578 chr1a   3166318 +       +       275     0
.       chrX    169941413       chrX    169942569       +       +       439     0
.       chrY    726435  chrY    737250  +       +       17      0

Would you please take a look for me? Thank you very much!!!!!!!!!! Looking forward to your reply😭
