### ISSUE TITLE
Clarification on `seg` format

### ISSUE THREAD

**Issue by b2jia** [lh3/hickit#30]
The current documentation on the seg format is sparse. Can someone help disambiguate the seg format? 

Below I've copied an example Dip-C read (GSE162511), delimited by `!`. While the first 3 fields are more or less decipherable, what do the last 4 fields correspond to?

```
K00261:212:HC2YYBBXY:7:1101:13443:1191  chr13!56249365!56249431!+!.!60!1        chr11!95992771!95992813!+!.!60!1
```

`chromosome | start coordinate | end coordinate | strand | haplotype? | score? | ? (always 1 or 2)`

**Comment by tanlongzhi** [comment]
Hi @b2jia, you're right that the 3rd last field is the haplotype, and the 2nd last field is mapping quality. You can find relevant code in the file hickit.js.

I'm not sure what the last field is. However, as far as I understand from code in io.c, the last field is NOT used in downstream analysis -- @lh3 please correct me if I'm wrong.

**Comment by lh3** [comment]
The last field counts the number of distant segments a read pair has. It is not actually used IIRC.

**Comment by b2jia** [comment]
Thank you both!
