### ISSUE TITLE
Dip-c included ?

### ISSUE THREAD

**Issue by Xparx** [lh3/hickit#33]
Hello,

I'm trying to follow the instructions from the documentation but I get stopped at first line 
```
# Map Dip-C reads and extract contacts (skip if you use your own pipeline)
./seqtk mergepe read1.fq.gz read2.fq.gz | ./pre-dip-c - | bwa mem -5SP -p hs37d5.fa - | gzip > aln.sam.gz
```
It says I need dip-c. In the dip-c repository it said that a faster better version is included in hickit.
If so; how do I use this version? If it's not included, dip-c is needed to be downloaded from the dip-c repo and can be used here?

Regards

**Comment by lh3** [comment]
See README: pre-dip-c is from https://github.com/lh3/pre-pe

**Comment by Xparx** [comment]
Thank you for the quick response. Working through understanding the pipeline. All good for this. :fist_right:

**Comment by lh3** [comment]
Good to know!
