### ISSUE TITLE
hickit-gl --view generate very small figure

### ISSUE THREAD

**Issue by Xparx** [lh3/hickit#34]
Hi, I am trying to visualize the 3d structure and things looks like they are working but I get a very small figure.
Is there anyway to scale the view option?
![hickit_gl_view](https://user-images.githubusercontent.com/715716/216121206-a8950ca7-9c35-4399-8247-03ec24cf8ca4.png)

Many thanks.

**Comment by lh3** [comment]
You may try to press keys from this part of the code (perhaps `,`/`<` or `.`/`>` will achieve what you want):

https://github.com/lh3/hickit/blob/75af3fad5fb0225c0fe4b1052412d674edb49759/view3d.c#L120-L171

**Comment by Xparx** [comment]
Hi, Thanks for the answer. 
Seems to me as the `,`, `.` keys move the plane of viewing but not zoom. If it's not just an odd behavior of my setup. The rest of the keys seems to work as expected. 

I also seem to have floating sequences that are too small to view on this view but when activating the "ball" mode I can view them as a cloud around the inner blob. I'm assuming that's why the main blob is so small.

**Comment by Xparx** [comment]
I think this is the fault of the files/pipeline I'm using.
