### ISSUE TITLE
Help with bulk Hi-C data

### ISSUE THREAD

**Issue by jeff-godwin** [lh3/hickit#37]
Dear hickit team,

I am using bulk Hi-C data from yeast for 3D modelling. It has been explicitly mentioned that the modelling functionality does not apply to bulk data. However this publication (https://www.nature.com/articles/s41594-019-0205-2 - **Analysis of 3D genome structures** under **Methods** section) has adopted the same with mice data. I'm wondering if I can tweak the pipeline for yeast data as well. It will be very helpful to know your thoughts.

I'm running a couple of iterations with my data. I will let you know if something comes up.

Thanks,
Jeffrey

**Comment by lh3** [comment]
hickit is not intended for modeling bulk Hi-C.
